### ISSUE TITLE
alpha colors corrupted

### ISSUE THREAD

**Issue by thisVioletHydra** [sbt/sbt-less#146]
before

```css
body {
 color: #0000 !important;
 background-color: #0000; 
}
```

after

```css
body {
  color: #000 0 !important;
  background-color: #000 0;
}

```

help 🗿
